In [14]:
# Patriots vs Seahawks Defensive Scouting Model

# Goal:
# Analyze Seattle's defense and identify offensive opportunities for New England.

# Questions:
# - How efficient is Seattle's defense?
# - Which downs are vulnerable?
# - Which areas of the field give up value?
# - Which concepts should the Patriots attack?

In [15]:
import nfl_data_py as nfl
import pandas as pd
import plotly.express as px

years = [2025]

pbp = nfl.import_pbp_data(years)

seattle = pbp[
    pbp["defteam"] == "SEA"
]

seattle = seattle[
    seattle["play_type"].isin(["pass","run"])
]

seattle.head()

2025 done.
Downcasting floats.

,play_id,game_id,old_game_id_x,home_team,away_team,season_type,week,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,drive,sp,qtr,down,goal_to_go,time,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,pass_length,pass_location,air_yards,yards_after_catch,run_location,run_gap,field_goal_result,kick_distance,extra_point_result,two_point_conv_result,home_timeouts_remaining,away_timeouts_remaining,timeout,timeout_team,td_team,td_player_name,td_player_id,posteam_timeouts_remaining,defteam_timeouts_remaining,total_home_score,total_away_score,posteam_score,defteam_score,score_differential,posteam_score_post,defteam_score_post,score_differential_post,no_score_prob,opp_fg_prob,opp_safety_prob,opp_td_prob,fg_prob,safety_prob,td_prob,extra_point_prob,two_point_conversion_prob,ep,epa,total_home_epa,total_away_epa,total_home_rush_epa,total_away_rush_epa,total_home_pass_epa,total_away_pass_epa,air_epa,yac_epa,comp_air_epa,comp_yac_epa,total_home_comp_air_epa,total_away_comp_air_epa,total_home_comp_yac_epa,total_away_comp_yac_epa,total_home_raw_air_epa,total_away_raw_air_epa,total_home_raw_yac_epa,total_away_raw_yac_epa,wp,def_wp,home_wp,away_wp,wpa,vegas_wpa,vegas_home_wpa,home_wp_post,away_wp_post,vegas_wp,vegas_home_wp,total_home_rush_wpa,total_away_rush_wpa,total_home_pass_wpa,total_away_pass_wpa,air_wpa,yac_wpa,comp_air_wpa,comp_yac_wpa,total_home_comp_air_wpa,total_away_comp_air_wpa,total_home_comp_yac_wpa,total_away_comp_yac_wpa,total_home_raw_air_wpa,total_away_raw_air_wpa,total_home_raw_yac_wpa,total_away_raw_yac_wpa,punt_blocked,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,fourth_down_converted,fourth_down_failed,incomplete_pass,touchback,interception,punt_inside_twenty,punt_in_endzone,punt_out_of_bounds,punt_downed,punt_fair_catch,kickoff_inside_twenty,kickoff_in_endzone,kickoff_out_of_bounds,kickoff_downed,kickoff_fair_catch,fumble_forced,fumble_not_forced,fumble_out_of_bounds,solo_tackle,safety,penalty,tackled_for_loss,fumble_lost,own_kickoff_recovery,own_kickoff_recovery_td,qb_hit,rush_attempt,pass_attempt,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown,extra_point_attempt,two_point_attempt,field_goal_attempt,kickoff_attempt,punt_attempt,fumble,complete_pass,assist_tackle,lateral_reception,lateral_rush,lateral_return,lateral_recovery,passer_player_id,passer_player_name,passing_yards,receiver_player_id,receiver_player_name,receiving_yards,rusher_player_id,rusher_player_name,rushing_yards,lateral_receiver_player_id,lateral_receiver_player_name,lateral_receiving_yards,lateral_rusher_player_id,lateral_rusher_player_name,lateral_rushing_yards,lateral_sack_player_id,lateral_sack_player_name,interception_player_id,interception_player_name,lateral_interception_player_id,lateral_interception_player_name,punt_returner_player_id,punt_returner_player_name,lateral_punt_returner_player_id,lateral_punt_returner_player_name,kickoff_returner_player_name,kickoff_returner_player_id,lateral_kickoff_returner_player_id,lateral_kickoff_returner_player_name,punter_player_id,punter_player_name,kicker_player_name,kicker_player_id,own_kickoff_recovery_player_id,own_kickoff_recovery_player_name,blocked_player_id,blocked_player_name,tackle_for_loss_1_player_id,tackle_for_loss_1_player_name,tackle_for_loss_2_player_id,tackle_for_loss_2_player_name,qb_hit_1_player_id,qb_hit_1_player_name,qb_hit_2_player_id,qb_hit_2_player_name,forced_fumble_player_1_team,forced_fumble_player_1_player_id,forced_fumble_player_1_player_name,forced_fumble_player_2_team,forced_fumble_player_2_player_id,forced_fumble_player_2_player_name,solo_tackle_1_team,solo_tackle_2_team,solo_tackle_1_player_id,solo_tackle_2_player_id,solo_tackle_1_player_name,solo_tackle_2_player_name,assist_tackle_1_player_id,assist_tackle_1_player_name,assist_tackle_1_team,assist_tackle_2_player_id,assist_tackle_2_player_name,assist_tackle_2_team,assist_tackle_3_player_id,assist_tackle_3_player_name,assist_tackle_3_team,assist_tackle_4_player_id,assist_tackle_4_player_name,assist_tackle_4_team,tackle_with_assist,tackle_with_assist_1_player_id,tackle_with_assist_1_player_name,tackle_with_assist_1_team,tackle_with_assist_2_player_id,tackle_with_assist_2_player_name,tackle_with_assist_2_team,pass_defense_1_player_id,pass_defense_1_player_name,pass_defense_2_player_id,pass_defense_2_player_name,fumbled_1_team,fumbled_1_player_id,fumbled_1_player_name,fumbled_2_player_id,fumbled_2_player_name,fumbled_2_team,fumble_recovery_1_team,fumble_recovery_1_yards,fumble_recovery_1_player_id,fumble_recovery_1_player_name,fumble_recovery_2_team,fumble_recovery_2_yards,fumble_recovery_2_player_id,fumble_recovery_2_player_name,sack_player_id,sack_player_name,half_sack_1_player_id,half_sack_1_player_name,half_sack_2_player_id,half_sack_2_player_name,return_team,return_yards,penalty_team,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv,safety_player_name,safety_player_id,season,cp,cpoe,series,series_success,series_result,order_sequence,start_time,time_of_day,stadium,weather,nfl_api_id,play_clock,play_deleted,play_type_nfl,special_teams_play,st_play_type,end_clock_time,end_yard_line,fixed_drive,fixed_drive_result,drive_real_start_time,drive_play_count,drive_time_of_possession,drive_first_downs,drive_inside20,drive_ended_with_score,drive_quarter_start,drive_quarter_end,drive_yards_penalized,drive_start_transition,drive_end_transition,drive_game_clock_start,drive_game_clock_end,drive_start_yard_line,drive_end_yard_line,drive_play_id_started,drive_play_id_ended,away_score,home_score,location,result,total,spread_line,total_line,div_game,roof,surface,temp,wind,home_coach,away_coach,stadium_id,game_stadium,aborted_play,success,passer,passer_jersey_number,rusher,rusher_jersey_number,receiver,receiver_jersey_number,pass,rush,first_down,special,play,passer_id,rusher_id,receiver_id,name,jersey_number,id,fantasy_player_name,fantasy_player_id,fantasy,fantasy_id,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe,nflverse_game_id,old_game_id_y,possession_team,offense_formation,offense_personnel,defenders_in_box,defense_personnel,number_of_pass_rushers,players_on_play,offense_players,defense_players,n_offense,n_defense,ngs_air_yards,time_to_throw,was_pressure,route,defense_man_zone_type,defense_coverage_type,offense_names,defense_names,offense_positions,defense_positions,offense_numbers,defense_numbers
2222,224.0,2025_01_SF_SEA,2025090709,SEA,SF,REG,1,SF,away,SEA,SF,95.0,2025-09-07,725.0,1625.0,3425.0,Half1,0.0,2.0,0.0,1.0,1.0,0,12:05,SF 5,10.0,95.0,(12:05) 13-B.Purdy pass short right to 23-C.Mc...,pass,3.0,0.0,0.0,1.0,0.0,0.0,0.0,short,right,3.0,0.0,None,None,None,NaN,None,None,3.0,3.0,0.0,None,None,None,None,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.005667,0.201656,0.023208,0.320505,0.177813,0.001633,0.269517,0.0,0.0,-0.471590,-0.429738,-0.572770,0.572770,-0.832225,0.832225,-0.203518,0.203518,-0.429738,0.0,-0.429738,0.0,-0.487592,0.487592,0.284074,-0.284074,-0.487592,0.487592,0.284074,-0.284074,0.471497,0.528503,0.528503,0.471497,-0.012785,0.008401,-0.008401,0.541288,0.458712,0.598760,0.401240,-0.042031,0.042031,-0.016415,0.016415,-0.012785,0.0,-0.012785,0.0,-0.034472,0.034472,0.018056,-0.018056,-0.034472,0.034472,0.018056,-0.018056,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,00-0037834,B.Purdy,3.0,00-0033280,C.McCaffrey,3.0,None,None,NaN,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,00-0031411,D.Lawrence,None,None,None,None,None,None,None,None,SEA,None,00-0039169,None,D.Witherspoon,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2025,0.532630,46.736969,3.0,1.0,First down,224.0,"9/7/25, 16:05:39",2025-09-07T20:13:17.123Z,Lumen Field,"Cloudy Temp: 67° F, Humidity: 83%, Wind: S 6 mph",f61ddd60-311e-11f0-b670-ae1250fadad1,0,0.0,PASS,0.0,None,2025-09-07T20:13:22.457Z,None,2.0,Touchdown,2025-09-07T20:13:17.123Z,14.0,8:22,6.0,1.0,1.0,1.0,1.0,10.0,PUNT,TOUCHDOWN,12:05,03:43,SF 5,SEA 5,224.0,642.0,17,13,Home,-4,30,-2.5,43.5,1,outdoors,fieldturf,67.0,6.0,Mike Macdonald,Kyle Shanahan,SEA00,Lumen Field,0.0,0.0,B.Purdy,13.0,None,NaN,C.McCaffrey,23.0,1.0,0.0,0.0,0.0,1.0,00-0037834,None,00-0033280,B.Purdy,13.0,00-0037834,C.McCaffrey,00-0033280,C.McCaffrey,00-0033280,0.0,1.0,-0.429738,0.685418,4.728233,3.0,0.557152,0.218603,0.301031,69.896935,2025_01_SF_SEA,2025090709,SF,UNDER CENTER,"1 C, 1 FB, 2 G, 1 QB, 1 RB, 2 T, 1 TE, 2 WR",6.0,"2 CB, 2 DT, 1 FS, 1 ILB, 1 MLB, 1 NT, 2 OLB, 1 SS",5.0,00-0032701;00-0037079;00-0039169;00-0031933;00...,00-0032701;00-0029892;00-0036272;00-0039351;00...,00-0037079;00-0039169;00-0031933;00-0039309;00...,11.0,11.0,NaN,3.6,1.0,QUICK OUT,ZONE_COVERAGE,COVER_6,Jake Brendel;Kyle Juszczyk;Ben Bartch;Dominick...,Riq Woolen;Devon Witherspoon;Leonard Williams;...,C;FB;G;G;QB;RB;T;T;TE;WR;WR,CB;CB;DT;DT;FS;ILB;MLB;NT;OLB;OLB;SS,64;44;78;77;13;23;71;68;85;15;1,27;21;99;91;8;48;13;90;0;53;20
2223,256.0,2025_01_SF_SEA,2025090709,SEA,SF,REG,1,SF,away,SEA,SF,92.0,2025-09-07,687.0,1587.0,3387.0,Half1,0.0,2.0,0.0,1.0,2.0,0,11:27,SF 8,7.0,95.0,(11:27) (Shotgun) 13-B.Purdy scrambles left gu...,run,3.0,1.0,0.0,1.0,0.0,0.0,1.0,None,None,NaN,NaN,left,guard,None,NaN,None,None,3.0,3.0,0.0,None,None,None,None,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.006299,0.214041,0.015304,0.349755,0.168739,0.001512,0.244349,0.0,0.0,-0.901328,-0.104161,-0.468610,0.468610,-0.728065,0.728065,-0.203518,0.203518,NaN,NaN,0.000000,0.0,-0.487592,0.487592,0.284074,-0.284074,-0.487592,0.487592,0.284074,-0.284074,0.458712,0.541288,0.541288,0.458712,-0.020443,-0.024493,0.024493,0.561732,0.438268,0.607161,0.392839,-0.021587,0.021587,-0.016415,0.016415,NaN,NaN,0.000000,0.0,-0.034472,0.034472,0.018056,-0.018056,-0.034472,0.034472,0.018056,-0.018056,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,None,None,NaN,00-0037834,B.Purdy,3.0,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,SEA,None,00-0038133,None,B.Mafe,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2025,NaN,NaN,3.0,1.0,First down,256.0,"9/7/25, 16:05:39",2025-09-07T20:13:54.400Z,Lumen Field,"Cloudy Temp: 67° F, Humidity: 83%, Wind: S 6 mph",f61ddd60-311e-11f0-b670-ae1250fadad1,0,0.0,RUSH,0.0,None,2025-09-07T20:14:01.187Z,None,2.0,Touchdown,2025-09-07T20:13:17.123Z,14.0,8:22,6.0,1.0,1.0,1.0,1.0,10.0,PUNT,TOUCHDOWN,12:05,03:43,SF 5,SEA 5,224.0,642.0,17,13,Home,-4,30,-2.5,43.5,1,outdoors,fieldturf,67.0,6.0,Mike Macdonald,Kyle Shanahan,SEA00,Lumen Field,0.0,0.0,B.Purdy,13.0,None,13.0,None,NaN,1.0,0.0,0.0,0.0,1.0,00-0037834,None,None,B.Purdy,13.0,00-0037834,B.Purdy,00-0037834,B.Purdy,00-0037834,0.0,1.0,-0.104161,NaN,NaN,NaN,NaN,NaN,0.588000,41.200001,2025_01_SF_SEA,2025090709,SF,SHOTGUN,"1 C, 1 FB, 2 G, 1 QB, 1 RB, 2 T, 1 TE, 2 WR",7.0,"2 CB, 2 DT, 1 FS, 1 ILB, 1 MLB, 2 OLB, 2 SS",4.0,00-0032701;00-0037079;00-0039169;00-0031933;00...,00-0032701;00-0029892;00-0036272;00-0039351;00...,00-0037079;00-0039169;00-0031933;00-0039309;00...,11.0,11.0,NaN,NaN,0.0,,ZONE_COVERAGE,COVER_2,Jake Brendel;Kyle Juszczyk;Ben Bartch;Dominick...,Riq Woolen;Devon Witherspoon;Leonard Williams;...,C;FB;G;G;QB;RB;T;T;TE;WR;WR,CB;CB;DT;DT;FS;ILB;MLB;OLB;OLB;SS;SS,64;44;78;77;13;23;71;68;85;15;1,27;21;99;91;8;48;13;0;53;20;3
2224,278.0,2025_01_SF_SEA,2025090709,SEA,SF,REG,1,SF,away,SEA,SF,89.0,2025-09-07,642.0,1542.0,3342.0,Half1,0.0,2.0,0.0,1.0,3.0,0,10:42,SF 11,4.0,95.0,(10:42) (Shotgun) 13-B.Purdy pass short right ...,pass,8.0,1.0,0.0,1.0,0.0,0.0,0.0,short,right,8.0,0.0,None,None,None,NaN,None,None,3.0,3.0,0.0,None,None,None,None,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.006538,0.233635,0.003581,0.354224,0.155418,0.002066,0.244538,0.0,0.0,-1.005488,1.347820,-1.816429,1.816429,-0.728065,0.728065,-1.551337,1.551337,1.347820,0.0,1.347820,0.0,-1.835412,1.835412,0.284074,-0.284074,-1.835412,1.835412,0.284074,-0.284074,0.438268,0.561732,0.561732,0.438268,0.044022,0.016113,-0.016113,0.517710,0.482290,0.582668,0.417332,-0.021587,0.021587,-0.060437,0.060437,0.044022,0.0,0.044022,0.0,-0.078494,0.078494,0.018056,-0.018056,-0.078494,0.078494,0.018056,-0.018056,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,00-0037834,B.Purdy,8.0,00-0033288,G.Kittle,8.0,None,None,NaN,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,SEA,None,00-0038136,None,C.Bryant,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2025,0.597597,40.240269,3.0,1.0,First down,278.0,"9/7/25, 16:05:39",2025-09-07T20:14:39.833Z,Lumen Field,"Cloudy Temp: 67° F, Humidity: 83%, Wind: S 6 mph",f61ddd60-311e-11f0-b670-ae1250fadad1,0,0.0,PASS,0.0,None,2025-09-07T20:14:44.473Z,None,2.0,Touchdown,2025-09-07T20:13:17.123Z,14.0,8:22,6.0,1.0,1.0,1.0,1.0,10.0,PUNT,TOUCHDOWN,12:05,03:43,SF 5,SEA 5,224.0,642.0,17,13,Home,-4,30,-2.5,43.5,1,outdoors,fieldturf,67.0,6.0,Mike Macdonald,Kyle Shanahan,SEA00,Lumen Field,0.0,1.0,B.Purdy,13.0,None,NaN,G.Kittle,85.0,1.0,0.0,1.0,0.0,1.0,00-0037834,None,00-0033288,B.Purdy,13.0,00-0037834,G.Kittle,00-0033288,G.Kittle,00-0033288,0.0,1.0,1.347820,0.266916,3.781073,1.0,0.999404,0.999404,0.930141,6.985855,2025_01_SF_SEA,2025090709,SF,SHOTGUN,"1 C, 2 G, 1 QB, 1 RB, 2 T, 1 TE, 3 WR",6.0,"3 CB, 2 DT, 1 FS, 1 MLB, 2 OLB, 2 SS",4.0,00-0032701;00-0037079;00-0037137;00-0039169;00...,00-0032701;00-0036272;00-0039351;00-0037834;00...,00-0037079;00-0037137;00-0039169;00-0031933;00...,11.0,11.0,NaN,2.4,0.0,DEEP OUT,MAN_COVERAGE,COVER_1,Jake Brendel;Ben Bartch;Dominick Puni;Brock Pu...,Riq Woolen;Josh Jobe;Devon Witherspoon;Leonard...,C;G;G;QB;RB;T;T;TE;WR;WR;WR,CB;CB;CB;DT;DT;FS;MLB;OLB;OLB;SS;SS,64;78;77;13;23;71;68;85;14;15;1,27;29;21;99;91;8;13;0;53;20;3
2225,303.0,2025_01_SF_SEA,2025090709,SEA,SF,REG,1,SF,away,SEA,SF,81.0,2025-09-07,600.0,1500.0,3300.0,Half1,0.0,2.0,0.0,1.0,1.0,0,10:00,SF 19,10.0,95.0,(10:00) (Shotgun) 23-C.McCaffrey left guard to...,run,4.0,1.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,left,guard,None,NaN,None,None,3.0,3.0,0.0,None,None,None,None,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.008824,0.164412,0.002414,0.294126,0.199124,0.003157,0.327942,0.0,0.0,0.342331,-0.147597,-1.668832,1.668832,-0.580467,0.580467,-1.551337,1.551337,NaN,NaN,0.000000,0.0,-1.835412,1.835412,0.284074,-0.284074,-1.835412,1.835412,0.284074,-0.284074,0.482290,0.517710,0.517710,0.482290,-0.000852,-0.002100,0.002100,0.518562,0.481438,0.598781,0.401219,-0.020735,0.020735,-0.060437,0.060437,NaN,NaN,0.000000,0.0,-0.078494,0.078494,0.018056,-0.018056,-0.078494,0.078494,0.018056,-0.018056,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,None,None,NaN,00-0033280,C.McCaffrey,4.0,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,SEA,None,00-0034974,None,J.Love,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2025,NaN,NaN,4.0,1.0,First down,303.0,"9/7/25, 16:05:39",2025-09-07T20:15:21.920Z,Lumen Field,"Cloudy Temp: 67° F, Humidity: 83%, Wind: S 6 mph",f61ddd60-311e-11f0-b670-ae1250fadad1,0,0.0,RUSH,0.0,None,2025-09-07T20:15:25.977Z,None,2.0,Touchdown,2025-09-07T20:13:17.123Z,14.0,8:22,6.0,1.0,1.0,1.0,1.0,10.0,PUNT,TOUCHDOWN,12:05,03:43,SF 5,SEA 5,224.0,642.0,17,13,Home,-4,30,-2.5,43.5,1,outdoors,fieldturf,67.0,6.0,Mike Macdonald,Kyle Shanahan,SEA00,Lumen Field,0.0,0.0,None,NaN,C.McCaffrey,23.0,None,NaN,0.0,1.0,0.0,0.0,1.0,None,00-0033280,None,C.McCaffrey,23.0,00-0033280,C.McCaffrey,00-0033280,C.McCaffrey,00-0033280,0.0,1.0,-0.147597,NaN,NaN,NaN,NaN,NaN,0.474196,-47.419609,2025_01_SF_SEA,2025090709,SF,SHOTGUN,"1 C, 1 FB, 2 G, 1 QB, 1 RB, 2 T, 1 TE, 2 WR",7.0,"2 CB, 2 DT, 1 FS, 1 ILB, 1 MLB, 1 NT, 1 OLB, 2 SS",0.0,00-0032701;00-0037079;00-0039169;00-0031933;00...,00-0032701;00-0029892;00-0036272;00-0039351;00...,00-0037079;00-0039169;00-0031933;00-0039309;00...,11.0,11.0,NaN,NaN,0.0,,,None,Jake Brendel;Kyle Juszczyk;Ben Bartch;Dominick...,Riq Woolen;Devon Witherspoon;Leonard Williams;...,C;FB;G;G;QB;RB;T;T;TE;WR;WR,CB;CB;DT;DT;FS;ILB;MLB;NT;OLB;SS;SS,64;44;78;77;13;23;71;68;85;15;1,27;21;99;91;8;48;13;90;0;20;3

In [16]:
explosive = seattle[
    seattle["yards_gained"] >= 15
]


explosive_rate = (
    len(explosive) /
    len(seattle)
)


print(
    f"Explosive play rate allowed: {explosive_rate:.2%}"
)

Explosive play rate allowed: 8.35%

In [17]:
negative = seattle[
    seattle["epa"] < 0
]


negative_rate = (
    len(negative) /
    len(seattle)
)


print(
    f"Negative play rate: {negative_rate:.2%}"
)

Negative play rate: 60.11%

In [18]:
down_epa = (

seattle
.groupby("down")
["epa"]
.mean()
.reset_index()

)

down_epa

   down       epa
0   1.0 -0.023333
1   2.0 -0.110971
2   3.0 -0.313457
3   4.0 -0.274172

In [19]:
fig = px.bar(
    down_epa,
    x="down",
    y="epa",
    title="Seattle EPA Allowed by Down"
)

fig.show()

In [20]:
coverage = seattle[
    seattle["play_type"]=="pass"
]


coverage_metrics = {

"Completion %":
coverage.complete_pass.mean(),

"Avg EPA":
coverage.epa.mean(),

"Avg Air Yards":
coverage.air_yards.mean()

}


pd.DataFrame(
coverage_metrics,
index=[0]
)

   Completion %   Avg EPA  Avg Air Yards
0      0.573472 -0.116765       7.241526

In [21]:
pressure = seattle[
    seattle["qb_hit"] == 1
]


print(
"QB hits:",
len(pressure)
)

QB hits: 129

In [22]:
sacks = seattle[
    seattle["sack"] == 1
]

print(
"Sacks:",
len(sacks)
)

Sacks: 56

In [23]:
route_defense = (

seattle
.groupby("route")
.agg(

EPA=("epa","mean"),
Attempts=("route","count"),
Yards=("yards_gained","mean")

)
.reset_index()

)


route_defense.sort_values(
"EPA"
)

                 route       EPA  Attempts      Yards
0                      -0.346445       550   2.696364
5               IN/DIG -0.201165        64   6.984375
3                   GO -0.094210        68   6.764706
8               SCREEN -0.059417        61   5.459016
13               WHEEL -0.057221         4   5.000000
7            QUICK OUT -0.045769       145   4.372414
11               SWING  0.013150        52   5.230769
4           HITCH/CURL  0.053877       111   5.855856
10               SLANT  0.086934        31   7.193548
9   SHALLOW CROSS/DRAG  0.123243        48   5.229167
2             DEEP OUT  0.147041        42   6.428571
1               CORNER  0.395312        31  11.483871
12         TEXAS/ANGLE  0.526179         6   7.666667
6                 POST  0.879932        33  14.424242

In [24]:
defense_score = {

"EPA Allowed":
seattle.epa.mean(),

"Explosive Rate":
explosive_rate,

"Negative Play Rate":
negative_rate,

"Success Allowed":
seattle.success.mean()

}


pd.DataFrame(
defense_score,
index=["Seattle"]
)

         EPA Allowed  Explosive Rate  Negative Play Rate  Success Allowed
Seattle    -0.123929        0.083467            0.601124         0.398876

In [25]:
patriots = pbp[
    (pbp["posteam"] == "NE") &
    (pbp["play_type"].isin(["pass","run"]))
]

patriots.head()

,play_id,game_id,old_game_id_x,home_team,away_team,season_type,week,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,drive,sp,qtr,down,goal_to_go,time,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,pass_length,pass_location,air_yards,yards_after_catch,run_location,run_gap,field_goal_result,kick_distance,extra_point_result,two_point_conv_result,home_timeouts_remaining,away_timeouts_remaining,timeout,timeout_team,td_team,td_player_name,td_player_id,posteam_timeouts_remaining,defteam_timeouts_remaining,total_home_score,total_away_score,posteam_score,defteam_score,score_differential,posteam_score_post,defteam_score_post,score_differential_post,no_score_prob,opp_fg_prob,opp_safety_prob,opp_td_prob,fg_prob,safety_prob,td_prob,extra_point_prob,two_point_conversion_prob,ep,epa,total_home_epa,total_away_epa,total_home_rush_epa,total_away_rush_epa,total_home_pass_epa,total_away_pass_epa,air_epa,yac_epa,comp_air_epa,comp_yac_epa,total_home_comp_air_epa,total_away_comp_air_epa,total_home_comp_yac_epa,total_away_comp_yac_epa,total_home_raw_air_epa,total_away_raw_air_epa,total_home_raw_yac_epa,total_away_raw_yac_epa,wp,def_wp,home_wp,away_wp,wpa,vegas_wpa,vegas_home_wpa,home_wp_post,away_wp_post,vegas_wp,vegas_home_wp,total_home_rush_wpa,total_away_rush_wpa,total_home_pass_wpa,total_away_pass_wpa,air_wpa,yac_wpa,comp_air_wpa,comp_yac_wpa,total_home_comp_air_wpa,total_away_comp_air_wpa,total_home_comp_yac_wpa,total_away_comp_yac_wpa,total_home_raw_air_wpa,total_away_raw_air_wpa,total_home_raw_yac_wpa,total_away_raw_yac_wpa,punt_blocked,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,fourth_down_converted,fourth_down_failed,incomplete_pass,touchback,interception,punt_inside_twenty,punt_in_endzone,punt_out_of_bounds,punt_downed,punt_fair_catch,kickoff_inside_twenty,kickoff_in_endzone,kickoff_out_of_bounds,kickoff_downed,kickoff_fair_catch,fumble_forced,fumble_not_forced,fumble_out_of_bounds,solo_tackle,safety,penalty,tackled_for_loss,fumble_lost,own_kickoff_recovery,own_kickoff_recovery_td,qb_hit,rush_attempt,pass_attempt,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown,extra_point_attempt,two_point_attempt,field_goal_attempt,kickoff_attempt,punt_attempt,fumble,complete_pass,assist_tackle,lateral_reception,lateral_rush,lateral_return,lateral_recovery,passer_player_id,passer_player_name,passing_yards,receiver_player_id,receiver_player_name,receiving_yards,rusher_player_id,rusher_player_name,rushing_yards,lateral_receiver_player_id,lateral_receiver_player_name,lateral_receiving_yards,lateral_rusher_player_id,lateral_rusher_player_name,lateral_rushing_yards,lateral_sack_player_id,lateral_sack_player_name,interception_player_id,interception_player_name,lateral_interception_player_id,lateral_interception_player_name,punt_returner_player_id,punt_returner_player_name,lateral_punt_returner_player_id,lateral_punt_returner_player_name,kickoff_returner_player_name,kickoff_returner_player_id,lateral_kickoff_returner_player_id,lateral_kickoff_returner_player_name,punter_player_id,punter_player_name,kicker_player_name,kicker_player_id,own_kickoff_recovery_player_id,own_kickoff_recovery_player_name,blocked_player_id,blocked_player_name,tackle_for_loss_1_player_id,tackle_for_loss_1_player_name,tackle_for_loss_2_player_id,tackle_for_loss_2_player_name,qb_hit_1_player_id,qb_hit_1_player_name,qb_hit_2_player_id,qb_hit_2_player_name,forced_fumble_player_1_team,forced_fumble_player_1_player_id,forced_fumble_player_1_player_name,forced_fumble_player_2_team,forced_fumble_player_2_player_id,forced_fumble_player_2_player_name,solo_tackle_1_team,solo_tackle_2_team,solo_tackle_1_player_id,solo_tackle_2_player_id,solo_tackle_1_player_name,solo_tackle_2_player_name,assist_tackle_1_player_id,assist_tackle_1_player_name,assist_tackle_1_team,assist_tackle_2_player_id,assist_tackle_2_player_name,assist_tackle_2_team,assist_tackle_3_player_id,assist_tackle_3_player_name,assist_tackle_3_team,assist_tackle_4_player_id,assist_tackle_4_player_name,assist_tackle_4_team,tackle_with_assist,tackle_with_assist_1_player_id,tackle_with_assist_1_player_name,tackle_with_assist_1_team,tackle_with_assist_2_player_id,tackle_with_assist_2_player_name,tackle_with_assist_2_team,pass_defense_1_player_id,pass_defense_1_player_name,pass_defense_2_player_id,pass_defense_2_player_name,fumbled_1_team,fumbled_1_player_id,fumbled_1_player_name,fumbled_2_player_id,fumbled_2_player_name,fumbled_2_team,fumble_recovery_1_team,fumble_recovery_1_yards,fumble_recovery_1_player_id,fumble_recovery_1_player_name,fumble_recovery_2_team,fumble_recovery_2_yards,fumble_recovery_2_player_id,fumble_recovery_2_player_name,sack_player_id,sack_player_name,half_sack_1_player_id,half_sack_1_player_name,half_sack_2_player_id,half_sack_2_player_name,return_team,return_yards,penalty_team,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv,safety_player_name,safety_player_id,season,cp,cpoe,series,series_success,series_result,order_sequence,start_time,time_of_day,stadium,weather,nfl_api_id,play_clock,play_deleted,play_type_nfl,special_teams_play,st_play_type,end_clock_time,end_yard_line,fixed_drive,fixed_drive_result,drive_real_start_time,drive_play_count,drive_time_of_possession,drive_first_downs,drive_inside20,drive_ended_with_score,drive_quarter_start,drive_quarter_end,drive_yards_penalized,drive_start_transition,drive_end_transition,drive_game_clock_start,drive_game_clock_end,drive_start_yard_line,drive_end_yard_line,drive_play_id_started,drive_play_id_ended,away_score,home_score,location,result,total,spread_line,total_line,div_game,roof,surface,temp,wind,home_coach,away_coach,stadium_id,game_stadium,aborted_play,success,passer,passer_jersey_number,rusher,rusher_jersey_number,receiver,receiver_jersey_number,pass,rush,first_down,special,play,passer_id,rusher_id,receiver_id,name,jersey_number,id,fantasy_player_name,fantasy_player_id,fantasy,fantasy_id,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe,nflverse_game_id,old_game_id_y,possession_team,offense_formation,offense_personnel,defenders_in_box,defense_personnel,number_of_pass_rushers,players_on_play,offense_players,defense_players,n_offense,n_defense,ngs_air_yards,time_to_throw,was_pressure,route,defense_man_zone_type,defense_coverage_type,offense_names,defense_names,offense_positions,defense_positions,offense_numbers,defense_numbers
1367,280.0,2025_01_LV_NE,2025090704,NE,LV,REG,1,NE,home,LV,NE,53.0,2025-09-07,731.0,1631.0,3431.0,Half1,0.0,2.0,0.0,1.0,1.0,0,12:11,NE 47,10.0,2.0,(12:11) (Shotgun) 10-D.Maye scrambles right en...,run,1.0,1.0,0.0,1.0,0.0,0.0,1.0,None,None,NaN,NaN,right,end,None,NaN,None,None,3.0,3.0,0.0,None,None,None,None,3.0,3.0,0.0,7.0,0.0,7.0,-7.0,0.0,7.0,-7.0,0.005084,0.092416,0.001416,0.145042,0.264881,0.004600,0.486561,0.0,0.0,2.914394,-0.515878,-5.345134,5.345134,-1.204066,1.204066,-5.684710,5.684710,NaN,NaN,0.0,0.0,-5.697483,5.697483,-0.591890,0.591890,-6.864604,6.864604,1.179894,-1.179894,0.427371,0.572629,0.427371,0.572629,-0.016429,-0.000365,-0.000365,0.410943,0.589057,0.446072,0.446072,-0.069454,0.069454,-0.141603,0.141603,NaN,NaN,0.0,0.0,-0.125244,0.125244,-0.031465,0.031465,-0.125244,0.125244,-0.016358,0.016358,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,None,None,NaN,00-0039851,D.Maye,1.0,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,LV,None,00-0037262,None,T.Booker,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2025,NaN,NaN,4.0,0.0,Punt,280.0,"9/7/25, 13:02:54",2025-09-07T17:12:03.140Z,Gillette Stadium,"Rain Temp: 64° F, Humidity: 86%, Wind: NE 4 mph",f5919f8e-311e-11f0-b670-ae1250fadad1,0,0.0,RUSH,0.0,None,2025-09-07T17:12:08.133Z,None,2.0,Punt,2025-09-07T17:11:21Z,3.0,1:43,0.0,0.0,0.0,1.0,1.0,0.0,KICKOFF,PUNT,12:17,10:34,NE 47,NE 49,250.0,347.0,20,13,Home,-7,33,2.5,44.5,0,outdoors,fieldturf,62.0,4.0,Mike Vrabel,Pete Carroll,BOS00,Gillette Stadium,0.0,0.0,D.Maye,10.0,None,10.0,None,NaN,1.0,0.0,0.0,0.0,1.0,00-0039851,None,None,D.Maye,10.0,00-0039851,D.Maye,00-0039851,D.Maye,00-0039851,0.0,0.0,-0.515878,NaN,NaN,NaN,NaN,NaN,0.470097,52.990276,2025_01_LV_NE,2025090704,NE,SHOTGUN,"1 C, 2 G, 1 QB, 1 RB, 2 T, 1 TE, 3 WR",6.0,"2 CB, 1 DE, 3 DT, 1 FS, 1 MLB, 2 OLB, 1 SS",4.0,00-0035588;00-0036901;00-0038381;00-0034973;00...,00-0035588;00-0036198;00-0040147;00-0039851;00...,00-0036901;00-0038381;00-0034973;00-0033381;00...,11.0,11.0,NaN,NaN,0.0,,MAN_COVERAGE,COVER_1,Garrett Bradbury;Mike Onwenu;Jared Wilson;Drak...,Eric Stokes;Kyu Kelly;Maxx Crosby;Adam Butler;...,C;G;G;QB;RB;T;T;TE;WR;WR;WR,CB;CB;DE;DT;DT;DT;FS;MLB;OLB;OLB;SS,65;71;58;10;38;76;66;85;8;13;9,22;36;98;69;99;96;20;52;45;57;11
1368,302.0,2025_01_LV_NE,2025090704,NE,LV,REG,1,NE,home,LV,NE,52.0,2025-09-07,687.0,1587.0,3387.0,Half1,0.0,2.0,0.0,1.0,2.0,0,11:27,NE 48,9.0,2.0,(11:27) 38-R.Stevenson up the middle to NE 49 ...,run,1.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,NaN,middle,None,None,NaN,None,None,3.0,3.0,0.0,None,None,None,None,3.0,3.0,0.0,7.0,0.0,7.0,-7.0,0.0,7.0,-7.0,0.006321,0.104858,0.001415,0.173531,0.260527,0.004876,0.448472,0.0,0.0,2.398515,-0.839863,-6.184996,6.184996,-2.043928,2.043928,-5.684710,5.684710,NaN,NaN,0.0,0.0,-5.697483,5.697483,-0.591890,0.591890,-6.864604,6.864604,1.179894,-1.179894,0.410943,0.589057,0.410943,0.589057,-0.022639,-0.038433,-0.038433,0.388303,0.611697,0.445707,0.445707,-0.092093,0.092093,-0.141603,0.141603,NaN,NaN,0.0,0.0,-0.125244,0.125244,-0.031465,0.031465,-0.125244,0.125244,-0.016358,0.016358,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,None,None,NaN,00-0036875,R.Stevenson,1.0,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,LV,None,00-0035707,None,D.White,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2025,NaN,NaN,4.0,0.0,Punt,302.0,"9/7/25, 13:02:54",2025-09-07T17:12:47Z,Gillette Stadium,"Rain Temp: 64° F, Humidity: 86%, Wind: NE 4 mph",f5919f8e-311e-11f0-b670-ae1250fadad1,0,0.0,RUSH,0.0,None,None,None,2.0,Punt,2025-09-07T17:11:21Z,3.0,1:43,0.0,0.0,0.0,1.0,1.0,0.0,KICKOFF,PUNT,12:17,10:34,NE 47,NE 49,250.0,347.0,20,13,Home,-7,33,2.5,44.5,0,outdoors,fieldturf,62.0,4.0,Mike Vrabel,Pete Carroll,BOS00,Gillette Stadium,0.0,0.0,None,NaN,R.Stevenson,38.0,None,NaN,0.0,1.0,0.0,0.0,1.0,None,00-0036875,None,R.Stevenson,38.0,00-0036875,R.Stevenson,00-0036875,R.Stevenson,00-0036875,0.0,0.0,-0.839863,NaN,NaN,NaN,NaN,NaN,0.672996,-67.299637,2025_01_LV_NE,2025090704,NE,UNDER CENTER,"1 C, 2 G, 1 QB, 1 RB, 2 T, 2 TE, 2 WR",8.0,"2 CB, 1 DE, 3 DT, 1 FS, 1 MLB, 2 OLB, 1 SS",0.0,00-0035588;00-0036901;00-0038381;00-0034973;00...,00-0035588;00-0036198;00-0040147;00-0039851;00...,00-0036901;00-0038381;00-0034973;00-0033381;00...,11.0,11.0,NaN,NaN,0.0,,,None,Garrett Bradbury;Mike Onwenu;Jared Wilson;Drak...,Eric Stokes;Kyu Kelly;Maxx Crosby;Adam Butler;...,C;G;G;QB;RB;T;T;TE;TE;WR;WR,CB;CB;DE;DT;DT;DT;FS;MLB;OLB;OLB;SS,65;71;58;10;38;76;66;85;81;13;9,22;36;98;69;99;96;20;52;45;57;11
1369,324.0,2025_01_LV_NE,2025090704,NE,LV,REG,1,NE,home,LV,NE,51.0,2025-09-07,646.0,1546.0,3346.0,Half1,0.0,2.0,0.0,1.0,3.0,0,10:46,NE 49,8.0,2.0,(10:46) (Shotgun) 10-D.Maye pass incomplete sh...,pass,0.0,1.0,0.0,1.0,0.0,0.0,0.0,short,right,11.0,NaN,None,None,None,NaN,None,None,3.0,3.0,0.0,None,None,None,None,3.0,3.0,0.0,7.0,0.0,7.0,-7.0,0.0,7.0,-7.0,0.007259,0.136830,0.001464,0.217068,0.235629,0.005517,0.396233,0.0,0.0,1.558653,-1.596529,-7.781525,7.781525,-2.043928,2.043928,-7.281238,7.281238,2.080199,-3.676727,0.0,0.0,-5.697483,5.697483,-0.591890,0.591890,-4.784405,4.784405,-2.496833,2.496833,0.388303,0.611697,0.388303,0.611697,-0.022544,-0.029962,-0.029962,0.365760,0.634241,0.407274,0.407274,-0.092093,0.092093,-0.164146,0.164146,0.0,-0.022544,0.0,0.0,-0.125244,0.125244,-0.031465,0.031465,-0.125244,0.125244,-0.038902,0.038902,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,00-0039851,D.Maye,NaN,00-0038621,D.Douglas,NaN,None,None,NaN,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2025,0.572098,-57.209785,4.0,0.0,Punt,324.0,"9/7/25, 13:02:54",2025-09-07T17:13:28.607Z,Gillette Stadium,"Rain Temp: 64° F, Humidity: 86%, Wind: NE 4 mph",f5919f8e-311e-11f0-b670-ae1250fadad1,0,0.0,PASS,0.0,None,2025-09-07T17:13:32.883Z,None,2.0,Punt,2025-09-07T17:11:21Z,3.0,1:43,0.0,0.0,0.0,1.0,1.0,0.0,KICKOFF,PUNT,12:17,10:34,NE 47,NE 49,250.0,347.0,20,13,Home,-7,33,2.5,44.5,0,outdoors,fieldturf,62.0,4.0,Mike Vrabel,Pete Carroll,BOS00,Gillette Stadium,0.0,0.0,D.Maye,10.0,None,NaN,D.Douglas,3.0,1.0,0.0,0.0,0.0,1.0,00-0039851,None,00-0038621,D.Maye,10.0,00-0039851,D.Douglas,00-0038621,D.Douglas,00-0038621,0.0,0.0,-1.596529,0.187604,3.110864,1.0,0.999146,0.999146,0.983819,1.618129,2025_01_LV_NE,2025090704,NE,SHOTGUN,"1 C, 2 G, 1 QB, 1 RB, 2 T, 1 TE, 3 WR",6.0,"3 CB, 3 DE, 1 DT, 1 FS, 2 OLB, 1 SS",4.0,00-0035588;00-0036394;00-0036901;00-0038381;00...,00-0035588;00-0036198;00-0040147;00-0039851;00...,00-0036394;00-0036901;00-0038381;00-0034973;00...,11.0,11.0,NaN,2.8,0.0,DEEP OUT,ZONE_COVERAGE,COVER_2,Garrett Bradbury;Mike Onwenu;Jared Wilson;Drak...,Darnay Holmes;Eric Stokes;Kyu Kelly;Maxx Crosb...,C;G;G;QB;RB;T;T;TE;WR;WR;WR,CB;CB;CB;DE;DE;DE;DT;FS;OLB;OLB;SS,65;71;58;10;38;76;66;85;13;9;3,30;22;36;98;51;9;69;20;45;57;11
1382,661.0,2025_01_LV_NE,2025090704,NE,LV,REG,1,NE,home,LV,NE,77.0,2025-09-07,382.0,1282.0,3082.0,Half1,0.0,4.0,0.0,1.0,1.0,0,06:22,NE 23,5.0,82.0,(6:22) 10-D.Maye scrambles left tackle to NE 2...,run,3.0,0.0,0.0,1.0,0.0,0.0,1.0,None,None,NaN,NaN,left,tackle,None,NaN,None,None,3.0,3.0,0.0,None,None,None,None,3.0,3.0,0.0,7.0,0.0,7.0,-7.0,0.0,7.0,-7.0,0.019180,0.138458,0.002107,0.233185,0.197129,0.002778,0.407163,0.0,0.0,1.395205,0.107013,-6.241430,6.241430,-1.867970,1.867970,-6.937401,6.937401,NaN,NaN,0.0,0.0,-8.902774,8.902774,-3.799206,3.799206,-12.990174,12.990174,4.746192,-4.746192,0.390052,0.609948,0.390052,0.609948,0.005179,0.006160,0.006160,0.395231,0.604769,0.401141,0.401141,-0.079499,0.079499,-0.158135,0.158135,NaN,NaN,0.0,0.0,-0.125244,0.125244,-0.201376,0.201376,-0.125244,0.125244,-0.065283,0.065283,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,None,NaN,None,None,NaN,00-0039851,D.Maye,3.0,None,None,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,LV,None,00-0033872,None,J.Adams,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,None,None,None,None,0.0,None,None,None,NaN,0.0,None,None,0.0,0.0,0.0,0.0,None,None,2025,NaN,NaN,9.0,1.0,First down,661.0,"9/7/25, 13:02:54",2025-09-07T17:27:20.867Z,Gillette Stadium,"Rain Temp: 64° F, Humidity: 86%, Wind: NE 4 mph",f5919f8e-311e-11f0-b670-ae1250fadad1,0,0.0,RUSH,0.0,None,2025-09-07T17:27:26.947Z,None,4.0,Touchdown,2025-09-07T17:26:36.640Z,12.0,5:20,5.0,1.0,1.0,1.0,1.0,5.0,INTERCEPTION,TOUCHDOWN,06:22,01:02,NE 18,LV 2,630.0,965.0,20,13,Home,-7,33,2.5,44.5,0,outdoors,fieldturf,62.0,4.0,Mike Vrabel,Pete Carroll,BOS00,Gillette Stadium,0.0,1.0,D.Maye,10.0,None,10.0,None,NaN,1.0,0.0,0.0,0.0,1.0,00-0039851,None,None,D.Maye,10.0,00-0039851,D.Maye,00-0039851,D.Maye,00-0039851,0.0,0.0,0.107013,NaN,NaN,NaN,NaN,NaN,0.423620,57.638042,2025_01_LV_NE,2025090704,NE,UNDER CENTER,"1 C, 2 G, 1 QB, 1 RB, 2 T, 2 TE, 2 WR",7.0,"2 CB, 2 DE, 2 DT, 1 FS, 1 MLB, 2 OLB, 1 SS",4.0,00-0035588;00-0036901;00-0038381;00-0034973;00...,00-0035588;00-0036198;00-0040147;00-0039851;00...,00-0036901;00-0038381;00-0034973;00-0038541;00...,11.0,11.0,NaN,NaN,0.0,,ZONE_COVERAGE,COVER_2,Garrett Bradbury;Mike Onwenu;Jared Wilson;Drak...,Eric Stokes;Kyu Kelly;Maxx Crosby;Tyree Wilson...,C;G;G;QB;RB;T;T;TE;TE;WR;WR,CB;CB;DE;DE;DT;DT;FS;MLB;OLB;OLB;SS,65;71;58;10;38;76;66;85;81;13;9,22;36;98;9;69;99;20;52;33;45;11

In [26]:
seattle_offense = seattle.groupby(
    "play_type"
).agg(

    EPA=("epa","mean"),
    Yards=("yards_gained","mean"),
    Success=("success","mean")

).reset_index()


seattle_offense

  play_type       EPA     Yards   Success
0      pass -0.116765  5.263979  0.412224
1       run -0.135479  3.926625  0.377358

In [27]:
down_attack = (

seattle
.groupby("down")
.agg(

EPA=("epa","mean"),
Success=("success","mean")

)
.reset_index()

)

down_attack

   down       EPA   Success
0   1.0 -0.023333  0.405825
1   2.0 -0.110971  0.406863
2   3.0 -0.313457  0.354478
3   4.0 -0.274172  0.489796

In [28]:
routes = (

patriots
.groupby("route")
.agg(

EPA=("epa","mean"),
Success=("success","mean"),
Targets=("route","count")

)
.reset_index()

)


routes.sort_values(
"EPA",
ascending=False
)

                 route       EPA   Success  Targets
1               CORNER  1.132907  0.645161       31
6                 POST  0.899902  0.647059       34
10               SLANT  0.756473  0.696970       33
3                   GO  0.651596  0.450704       71
5               IN/DIG  0.521606  0.584615       65
9   SHALLOW CROSS/DRAG  0.455699  0.675000       40
7            QUICK OUT  0.285926  0.594595      111
12         TEXAS/ANGLE  0.282988  1.000000        1
4           HITCH/CURL  0.198614  0.600000      110
8               SCREEN  0.114934  0.444444       36
2             DEEP OUT  0.106507  0.476190       42
11               SWING  0.052506  0.392857       28
13               WHEEL -0.029467  0.375000        8
0                      -0.212039  0.365297      657

In [29]:
attack_plan = routes.merge(
    route_defense,
    on="route",
    suffixes=("_NE","_SEA")
)


attack_plan["Matchup_Score"] = (

attack_plan["EPA_NE"]
*
attack_plan["EPA_SEA"]

)


attack_plan.sort_values(
"Matchup_Score",
ascending=False
)

,route,EPA_NE,Success,Targets,EPA_SEA,Attempts,Yards,Matchup_Score
6,POST,0.899902,0.647059,34,0.879932,33,14.424242,0.791852
1,CORNER,1.132907,0.645161,31,0.395312,31,11.483871,0.447852
12,TEXAS/ANGLE,0.282988,1.000000,1,0.526179,6,7.666667,0.148902
0,,-0.212039,0.365297,657,-0.346445,550,2.696364,0.073460
10,SLANT,0.756473,0.696970,33,0.086934,31,7.193548,0.065763
9,SHALLOW CROSS/DRAG,0.455699,0.675000,40,0.123243,48,5.229167,0.056162
2,DEEP OUT,0.106507,0.476190,42,0.147041,42,6.428571,0.015661
4,HITCH/CURL,0.198614,0.600000,110,0.053877,111,5.855856,0.010701
13,WHEEL,-0.029467,0.375000,8,-0.057221,4,5.000000,0.001686
11,SWING,0.052506,0.392857,28,0.013150,52,5.230769,0.000690
8,SCREEN,0.114934,0.444444,36,-0.059417,61,5.459016,-0.006829
7,QUICK OUT,0.285926,0.594595,111,-0.045769,145,4.372414,-0.013087
3,GO,0.651596,0.450704,71,-0.094210,68,6.764706,-0.061387
5,IN/DIG,0.521606,0.584615,65,-0.201165,64,6.984375,-0.104929

In [30]:
explosive_allowed = seattle[
    seattle["yards_gained"] >= 20
]


explosive_allowed.groupby(
"pass_location"
).size()

pass_location
left      20
middle    11
right     27
dtype: int64

In [31]:
attack_plan["Final_Attack_Score"] = (

attack_plan["Matchup_Score"]
*
attack_plan["Targets"]

)


attack_plan.sort_values(
"Final_Attack_Score",
ascending=False
).head(10)

,route,EPA_NE,Success,Targets,EPA_SEA,Attempts,Yards,Matchup_Score,Final_Attack_Score
0,,-0.212039,0.365297,657,-0.346445,550,2.696364,0.073460,48.263140
6,POST,0.899902,0.647059,34,0.879932,33,14.424242,0.791852,26.922966
1,CORNER,1.132907,0.645161,31,0.395312,31,11.483871,0.447852,13.883405
9,SHALLOW CROSS/DRAG,0.455699,0.675000,40,0.123243,48,5.229167,0.056162,2.246479
10,SLANT,0.756473,0.696970,33,0.086934,31,7.193548,0.065763,2.170176
4,HITCH/CURL,0.198614,0.600000,110,0.053877,111,5.855856,0.010701,1.177089
2,DEEP OUT,0.106507,0.476190,42,0.147041,42,6.428571,0.015661,0.657762
12,TEXAS/ANGLE,0.282988,1.000000,1,0.526179,6,7.666667,0.148902,0.148902
11,SWING,0.052506,0.392857,28,0.013150,52,5.230769,0.000690,0.019333
13,WHEEL,-0.029467,0.375000,8,-0.057221,4,5.000000,0.001686,0.013489